---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__(<p>__start__</p>)
	await_player(await_player)
	prepare(prepare)
	organize(organize)
	agent(agent)
	resolve(resolve)
	finalize(finalize)
	coach(coach)
	commit(commit)
	__end__(<p>__end__</p>)
	__start__ --> await_player;
	await_player --> prepare;
	prepare --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
